# Commands
# {5} >> Delay 5 ticks
# [playercmd] <cmd>
# [opplayercmd] <cmd>
# [consolecmd] <cmd>
# [tele] <location>
# [mess] <message>
# [broadcast] <message>
# [title] <title;subtitle>
# [kill] <mob;mob2(*=all)(slave=slave)>
# [sound] <sound>;f1;f2
# [showrank]
# Rank: S, A, B, C, D, F

sound-play:
  on-resourcepack-load:
    delay: 0
    play-times: 3
    sounds:
      - theme1
  on-start-dungeon:
    delay: 10
    play-times: -1
    sounds:
      - background1
      - background2
      - background3
      - background4
      - background5
      - background6
      - background7
      - background8
  on-boss-dungeon:
    delay: 10
    play-times: -1
    sounds:
      - boss1
      - boss2
      - boss3
      - boss4
  on-win-dungeon:
    delay: 0
    play-times: 1
    sounds:
      - victory1
      - victory2
      - victory3
sounds:
  background1:
    source: 'dungeon.background.1'
    length: 15484
  background2:
    source: 'dungeon.background.2'
    length: 10105
  background3:
    source: 'dungeon.background.3'
    length: 21333
  background4:
    source: 'dungeon.background.4'
    length: 13091
  background5:
    source: 'dungeon.background.5'
    length: 20426
  background6:
    source: 'dungeon.background.6'
    length: 13241
  background7:
    source: 'dungeon.background.7'
    length: 16000
  background8:
    source: 'dungeon.background.8'
    length: 12000
  theme1:
    source: 'dungeon.theme.1'
    length: 20211
  victory1:
    source: 'dungeon.victory.1'
    length: 7416
  victory2:
    source: 'dungeon.victory.2'
    length: 8332
  victory3:
    source: 'dungeon.victory.3'
    length: 4000
  boss1:
    source: 'dungeon.boss.1'
    length: 12000
  boss2:
    source: 'dungeon.boss.2'
    length: 17455
  boss3:
    source: 'dungeon.boss.3'
    length: 19200
  boss4:
    source: 'dungeon.boss.4'
    length: 22818

room:
  room-limit: 10
  world-last-time: 3600
  room-count-down: 60
  remove-room-count-down: 5

world:
  world_template_1:
    # NORMAL/NETHER/THE_END
    environment: NORMAL
    # Can add if u need those behind
    #type: NORMAL
    #seed: 0
    #generator: something

featherboard:
  enable: true
  board: dungeon

ticket:
  item:
    name: '&6&lVé phó bản &e&l%dungeon_name%'
    type: DIAMOND
    data: 13
    lore:
    - '&7&oDùng để vào hàng chờ phó bản'
    enchant: []
    flag: []

buff:
  drop: 1.5

rank:
  S:
    kill: 90
    save: 90
    time: 20
    dead: 0
  A:
    kill: 75
    save: 75
    time: 30
    dead: 0
  B:
    kill: 60
    save: 60
    time: 40
    dead: 50
  C:
    kill: 40
    save: 40
    time: 50
    dead: 50
  D:
    kill: 20
    save: 20
    time: 60
    dead: 100
  F:
    kill: 10
    save: 10
    time: 70
    dead: 100

# Professions:
# 1: Default + tạp đề
# 2: Default
# 3: White
# 4: Purple
# 5: Default + black shirt
# 6: 1
# 7: Green
# 8: 1
slave:
  slv1:
    name: '&6&lSteve'
    color: 2
  slv2:
    name: '&f&lJohn'
    color: 3

guarded:
  g1:
   name: '&f&lJohn'
   color: 3
   health: 30
   target-radius: 10

gui:
  size: 27
  background:
    slots: [1, 10, 19]
    item:
      name: '&f'
      type: GLASS_PANE
      data: 21
      lore: []
      enchant: []
      flag: []
  tutorial:
    slot: 0
    item:
      name: '&a&lPhó bản (Dungeon) là gì ?'
      type: GLASS_PANE
      data: 25
      lore:
        - ''
        - '&f&oLà nơi bạn chiến đấu với quái vật, '
        - '&f&otừ đó nhận được các phần quà'
        - '&f&otùy thuộc vào các phó bản'
        - ''
        - '&f&oĐể tham gia phó bản, bạn phải '
        - '&f&ođợi người tham gia trước kết thúc '
        - '&f&orồi bạn mới có thể vào'
        - ''
        - '&f&oMột số phó bản yêu cầu &6Vé Phó bản'
        - '&f&ovà bạn có thể mua ở cửa hàng'
      enchant: []
      flag: []
  info:
    slot: 9
    item:
      name: '&a&lThông tin của bạn'
      type: GLASS_PANE
      data: 8
      lore:
        - '&6Buff tỉ lệ rơi đồ: &e%dungeon_buff_drop%'
        - '&6Buff hồi sinh: &e%dungeon_buff_revive% lượt'
        - '&6Vượt phó bản: &e%sora_dungeon_win_times% lần'
        - '&6Thua phó bản: &e%sora_dungeon_lose_times% lần'
        - '&6Hạ gục: &e%sora_dungeon_mob_killed% quái'
      enchant: []
      flag: []
  quit:
    slot: 18
    item:
      name: '&c&lThoát'
      type: GLASS_PANE
      data: 24
      lore: []
      enchant: []
      flag: []
