# **Commands
# {5} >> Delay 5 ticks, [playercmd] <cmd>, [opplayercmd] <cmd>, [consolecmd] <cmd>,[tele] <location>, [mess] <message>, [broadcast] <message>, [title] <title;subtitle>, [kill] <mob;mob2(*=all)(slave=slave)>, [sound] <sound>;f1;f2, [showrank]
# **Available GUI Dungeon Slots: 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26

# Buff rate
buff:
  drop: 0.5

# Featherboard hook
featherboard:
  enable: true
  board: dungeon

# Ticket item
ticket:
  item:
    name: '&6&lVé &e&l%dungeon_name%'
    type: GOLD_INGOT
    data: 4
    lore:
    - '&7&oDùng để vào hàng chờ phó bản'
    enchant: []
    flag: []

# Rank requirement
rank:
  S:
    kill: 90
    save: 90
    time: 20
    dead: 0
  A:
    kill: 75
    save: 75
    time: 30
    dead: 0
  B:
    kill: 60
    save: 60
    time: 40
    dead: 50
  C:
    kill: 40
    save: 40
    time: 50
    dead: 50
  D:
    kill: 20
    save: 20
    time: 60
    dead: 100
  F:
    kill: 10
    save: 10
    time: 70
    dead: 100

# **Slave & Guarded color
# 1, 6, 8: Default + tạp đề
# 2: Default
# 3: White
# 4: Purple
# 5: Default + Áo đen
# 7: Green
slave:
  slv1:
    name: '&6&lSteve'
    color: 2
  slv2:
    name: '&f&lJohn'
    color: 3
guarded:
  g1:
   name: '&f&lJohn'
   color: 3
   health: 30
   target-radius: 10

# GUI
gui:
  size: 27
  background:
    slots: [1, 10, 19]
    item:
      name: '&f'
      type: GLASS_PANE
      data: 21
      lore: []
      enchant: []
      flag: []
  tutorial:
    slot: 0
    item:
      name: '&a&lPhó bản (Dungeon) là gì ?'
      type: GLASS_PANE
      data: 25
      lore:
        - ''
        - '&f&oLà nơi bạn chiến đấu với quái vật, '
        - '&f&otừ đó nhận được các phần quà'
        - '&f&otùy thuộc vào các phó bản'
        - ''
        - '&f&oĐể tham gia phó bản, bạn phải '
        - '&f&ođợi người tham gia trước kết thúc '
        - '&f&orồi bạn mới có thể vào'
        - ''
        - '&f&oMột số phó bản yêu cầu &6Vé Phó bản'
        - '&f&ovà bạn có thể mua ở cửa hàng'
      enchant: []
      flag: []
  info:
    slot: 9
    item:
      name: '&a&lThông tin của bạn'
      type: GLASS_PANE
      data: 8
      lore:
        - '&6Buff tỉ lệ rơi đồ: &e%dungeon_buff_drop%'
        - '&6Buff hồi sinh: &e%dungeon_buff_revive% lượt'
        - '&6Vượt phó bản: &e%sora_dungeon_win_times% lần'
        - '&6Thua phó bản: &e%sora_dungeon_lose_times% lần'
        - '&6Hạ gục: &e%sora_dungeon_mob_killed% quái'
      enchant: []
      flag: []
  quit:
    slot: 18
    item:
      name: '&c&lThoát'
      type: GLASS_PANE
      data: 24
      lore: []
      enchant: []
      flag: []

    