# Commands
# {5} >> Delay 5 ticks
# [playercmd] <cmd>
# [opplayercmd] <cmd>
# [consolecmd] <cmd>
# [tele] <location>
# [mess] <message>
# [broadcast] <message>
# [title] <title;subtitle>
# [kill] <mob;mob2(*=all)(slave=slave)>
# [sound] <sound>;f1;f2
# [showrank]
# Rank: S, A, B, C, D, F

world:
  world_template_1:
    # NORMAL/NETHER/THE_END
    environment: NORMAL
    # Can add if u need those behind
    #type: NORMAL
    #seed: 0
    #generator: something

featherboard:
  enable: true
  board: dungeon

ticket:
  item:
    name: '&6&lVé phó bản &e&l%dungeon_name%'
    type: DIAMOND
    data: 13
    lore:
    - '&7&oDùng để vào hàng chờ phó bản'
    enchant: []
    flag: []

buff:
  drop: 1.5

rank:
  S:
    kill: 90
    save: 90
    time: 20
    dead: 0
  A:
    kill: 75
    save: 75
    time: 30
    dead: 0
  B:
    kill: 60
    save: 60
    time: 40
    dead: 50
  C:
    kill: 40
    save: 40
    time: 50
    dead: 50
  D:
    kill: 20
    save: 20
    time: 60
    dead: 100
  F:
    kill: 10
    save: 10
    time: 70
    dead: 100

# Professions:
# 1: Default + tạp đề
# 2: Default
# 3: White
# 4: Purple
# 5: Default + black shirt
# 6: 1
# 7: Green
# 8: 1
slave:
  slv1:
    name: '&6&lSteve'
    color: 2
  slv2:
    name: '&f&lJohn'
    color: 3

guarded:
  g1:
   name: '&f&lJohn'
   color: 3
   health: 30
   target-radius: 10